[project]
name = "webhook-alert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.5",
    "httpx>=0.27.2",
    "uvicorn>=0.32.0",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
