[project]
name = "webhook-alert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.5",
    "httpx>=0.27.2",
]

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
